name: Deploy new docker container

on:
  push:
    tags:
      - 'V*'

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: | 
            marshallasch/ns3:${{ GITHUB_REF }}
            marshallasch/ns3:latest
            marshallasch/ns3:ns3-3.32

