name: Create Docker Container

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #profile: ['debug', 'optimized']
        ns3: [3.32, 3.33, 3.34, 3.35]
    steps:
      - name: Setup the current date
        id: prep
        run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: marshallasch/ns3-action
          tags: |
            type=sha,format=short,prefix=${{ matrix.ns3 }}-,suffix=
            type=raw,value=ns3-${{ matrix.ns3 }}
            type=semver,pattern={{version}},suffix=-${{ matrix.ns3 }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_DATE=${{ steps.date.outputs.date }}
            VCS_REF=${{ github.sha }}
            NS3_VERSION=${{ matrix.ns3 }}
